apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain

  awsElasticBlockStore:
    volumeID: vol-003fa5d2cf8cd1bf8
    fsType: ext4
