apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql

spec:
  replicas: 1

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_DATABASE

          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d

            # ✅ PVC mount added
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: init-sql
          configMap:
            name: mysql-initdb

        # ✅ PVC added here
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: ebs-pvc
